# Generated by Django 5.0.2 on 2024-03-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_team'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.team'),
        ),
    ]
